/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/Section`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/alerts` | `/alerts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/driving` | `/driving`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/eeg` | `/eeg`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sleep` | `/sleep`; params?: Router.UnknownInputParams; } | { pathname: `/components/Card`; params?: Router.UnknownInputParams; } | { pathname: `/components/MetricBadge`; params?: Router.UnknownInputParams; } | { pathname: `/components/Section`; params?: Router.UnknownInputParams; } | { pathname: `/firebase/config`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useDeviceSignals`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useRealtimeStats`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/Section`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/alerts` | `/alerts`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/driving` | `/driving`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/eeg` | `/eeg`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/sleep` | `/sleep`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Card`; params?: Router.UnknownOutputParams; } | { pathname: `/components/MetricBadge`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Section`; params?: Router.UnknownOutputParams; } | { pathname: `/firebase/config`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/useDeviceSignals`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/useRealtimeStats`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/Section${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/alerts${`?${string}` | `#${string}` | ''}` | `/alerts${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/driving${`?${string}` | `#${string}` | ''}` | `/driving${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/eeg${`?${string}` | `#${string}` | ''}` | `/eeg${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/sleep${`?${string}` | `#${string}` | ''}` | `/sleep${`?${string}` | `#${string}` | ''}` | `/components/Card${`?${string}` | `#${string}` | ''}` | `/components/MetricBadge${`?${string}` | `#${string}` | ''}` | `/components/Section${`?${string}` | `#${string}` | ''}` | `/firebase/config${`?${string}` | `#${string}` | ''}` | `/hooks/useDeviceSignals${`?${string}` | `#${string}` | ''}` | `/hooks/useRealtimeStats${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/Section`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/alerts` | `/alerts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/driving` | `/driving`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/eeg` | `/eeg`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sleep` | `/sleep`; params?: Router.UnknownInputParams; } | { pathname: `/components/Card`; params?: Router.UnknownInputParams; } | { pathname: `/components/MetricBadge`; params?: Router.UnknownInputParams; } | { pathname: `/components/Section`; params?: Router.UnknownInputParams; } | { pathname: `/firebase/config`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useDeviceSignals`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useRealtimeStats`; params?: Router.UnknownInputParams; };
    }
  }
}
